<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "e_annuaires"
 *
 * Auto generated by Extension Builder 2013-10-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Annuaires',
	'description' => '',
	'category' => 'plugin',
	'author' => 'xley',
	'author_email' => 'xley@e-magineurs.com',
	'author_company' => 'e-magineurs',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.3.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>